package relational

import (
	"maps"
	"slices"
)

// Column - A column as the database catalog describes it
type Column struct {
	Type    string // format_type(atttypid, atttypmod)
	NotNull bool
	// Default - pg_get_expr(adbin, adrelid), "" when none. For a generated
	// column it is the generation expression
	Default   string
	Generated bool   // attgenerated <> ''
	Identity  string // attidentity: "" when none, "a" ALWAYS, "d" BY DEFAULT
	// VolatileDefault is only known for the desired catalog, and only for a
	// column its live table lacks: adding the column would rewrite the table
	// because the default is volatile
	VolatileDefault bool
}

// Table - A table as the database catalog describes it
type Table struct {
	Columns     map[string]Column
	Indexes     map[string]string // name -> canonical definition
	Constraints map[string]string // name -> pg_get_constraintdef
}

// Catalog - The tables of one namespace by name
type Catalog map[string]Table

// definition - The canonical text two columns are compared by: type,
// nullability, default or generation expression, and identity
func (c Column) definition() string {
	definition := c.Type
	if c.NotNull {
		definition += " NOT NULL"
	}

	switch {
	case c.Generated:
		definition += " GENERATED ALWAYS AS (" + c.Default + ") STORED"
	case c.Default != "":
		definition += " DEFAULT " + c.Default
	}

	switch c.Identity {
	case "a":
		definition += " GENERATED ALWAYS AS IDENTITY"
	case "d":
		definition += " GENERATED BY DEFAULT AS IDENTITY"
	}

	return definition
}

// diff - Compares a desired catalog with a live one. A table missing from
// either side is one change, without its columns, indexes or constraints.
// Output is sorted by table, then kind, then name
func diff(desired, live Catalog) Plan {
	var plan Plan

	for _, name := range slices.Sorted(maps.Keys(desired)) {
		have, ok := live[name]
		if !ok {
			plan.Missing = append(plan.Missing, Change{Kind: "table", Table: name, Name: name})
			continue
		}

		want := desired[name]
		plan = diffObjects(plan, "column", name, columnDefinitions(want.Columns), columnDefinitions(have.Columns))
		plan = diffObjects(plan, "index", name, want.Indexes, have.Indexes)
		plan = diffObjects(plan, "constraint", name, want.Constraints, have.Constraints)
	}

	for _, name := range slices.Sorted(maps.Keys(live)) {
		_, ok := desired[name]
		if !ok {
			plan.Extra = append(plan.Extra, Change{Kind: "table", Table: name, Name: name})
		}
	}

	return plan
}

// diffObjects - Adds the changes between one table's declared and live
// objects of a kind, given as name -> canonical definition
func diffObjects(plan Plan, kind, table string, want, have map[string]string) Plan {
	for _, name := range slices.Sorted(maps.Keys(want)) {
		change := Change{Kind: kind, Table: table, Name: name, Want: want[name]}

		haveDefinition, ok := have[name]
		if !ok {
			plan.Missing = append(plan.Missing, change)
			continue
		}

		if haveDefinition != want[name] {
			change.Have = haveDefinition
			plan.Different = append(plan.Different, change)
		}
	}

	for _, name := range slices.Sorted(maps.Keys(have)) {
		_, ok := want[name]
		if !ok {
			plan.Extra = append(plan.Extra, Change{Kind: kind, Table: table, Name: name, Have: have[name]})
		}
	}

	return plan
}

// columnDefinitions - Columns as name -> canonical definition
func columnDefinitions(columns map[string]Column) map[string]string {
	definitions := make(map[string]string, len(columns))
	for name, column := range columns {
		definitions[name] = column.definition()
	}

	return definitions
}
